[options]
admin_passwd = ${ODOO_ADMIN_PASSWORD}
db_host = ${HOST}
db_port = ${DB_PORT}
db_user = ${SERVICE_USER_POSTGRES}
db_password = ${SERVICE_PASSWORD_POSTGRES}
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
limit_time_cpu = ${ODOO_LIMIT_TIME_CPU}
limit_time_real = ${ODOO_LIMIT_TIME_REAL}
workers = ${ODOO_WORKERS}

http_port = 8069
proxy_mode = True

; Filter only selected DB
;dbfilter = ^${ODOO_DATABASE}$